name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Check Server
        run: |
          whoami
          hostname
          pwd
          docker --version
          docker compose version